import re, os
import numpy as np
import torch
import json
from botorch.utils.multi_objective.pareto import is_non_dominated

def get_weights_from_filename(filename):
    """
    Extracts the list of weights from a filename generated by the optimization script.

    Args:
        filename (str): The full filename, e.g., 'data/optimization_results_0p05_0p05_0p9.csv'.

    Returns:
        list: A list of floats representing the weights.
    """
    # Define a pattern to find the weight part of the filename
    # This looks for any file that starts with "gp_minimize_result_" or "optimization_results_"
    # and ends with a file extension like .pkl or .csv
    pattern = r'(?:gp_minimize_result_|optimization_results_)(.*)\.(?:pkl|csv)'

    match = re.search(pattern, os.path.basename(filename))
    
    if match:
        weights_string = match.group(1)
        # Replace 'p' with '.' and split the string by underscores
        weight_parts = weights_string.replace('p', '.').split('_')
        
        # Convert each string part to a float and return as a list
        try:
            weights = [float(w) for w in weight_parts]
            return weights
        except ValueError:
            print(f"Error: Could not convert weight parts to floats: {weight_parts}")
            return None
    else:
        print(f"Error: Filename format not recognized: {filename}")
        return None

###########################################################################################

def save_results(train_X, train_Y, file_prefix="mobo_results/mobo_results"):
    """Saves the optimization results to JSON and CSV files."""
    data = {
        "parameters": train_X.tolist(),
        "objectives": train_Y.tolist()
    }
    with open(f"{file_prefix}.json", "w") as f:
        json.dump(data, f, indent=2)

    # Note: These CSVs will contain negated objectives if train_Y is negated
    # You might want to save the original scale if needed for external analysis
    pareto_mask = is_non_dominated(train_Y)
    pareto_Y = train_Y[pareto_mask]
    np.savetxt(f"{file_prefix}_pareto_negated.csv", pareto_Y.numpy(), delimiter=",", 
               header="emit_x_neg,emit_y_neg,sigma_energy_neg") # Removed .cpu()
    np.savetxt(f"{file_prefix}_params.csv", train_X.numpy(), delimiter=",", 
               header=','.join([f"param_{i}" for i in range(train_X.shape[1])])) # Removed .cpu()
    np.savetxt(f"{file_prefix}_objectives_negated.csv", train_Y.numpy(), delimiter=",", 
               header="emit_x_neg,emit_y_neg,sigma_energy_neg") # Removed .cpu()
    print (f"Results saved to {file_prefix}.json, {file_prefix}_pareto_negated.csv, {file_prefix}_params.csv, {file_prefix}_objectives_negated.csv")

###########################################################################################

def save_checkpoint(iteration, train_X, train_Y, train_feas_mask, hypervolumes, 
                    train_constraints_list, acquisition_mode, 
                    checkpoint_file="mobo_results/mobo_checkpoint.pt"):
    """Saves the current state of the Bayesian Optimization."""
    checkpoint_data = {
        'iteration': iteration,
        'train_X': train_X,
        'train_Y': train_Y,
        'train_feas_mask': train_feas_mask,
        'hypervolumes': hypervolumes,
        'train_constraints_list': train_constraints_list,
        'acquisition_mode': acquisition_mode
    }
    torch.save(checkpoint_data, checkpoint_file)
    print(f"Checkpoint saved at iteration {iteration} to {checkpoint_file}")

###########################################################################################

def load_checkpoint(checkpoint_file="mobo_results/mobo_checkpoint.pt"):
    """Loads the state of the Bayesian Optimization from a checkpoint."""
    if os.path.exists(checkpoint_file):
        print(f"Loading checkpoint from {checkpoint_file}...")
        checkpoint_data = torch.load(checkpoint_file, weights_only=False)
        print(f"Checkpoint loaded. Resuming from iteration {checkpoint_data['iteration'] + 1}.")
        return checkpoint_data
    else:
        print("No checkpoint found. Starting new optimization.")
        return None
    