import re, os
import numpy as np
import torch
import json
from botorch.utils.multi_objective.pareto import is_non_dominated

def get_weights_from_filename(filename):
    """
    Extracts the list of weights from a filename generated by the optimization script.

    Args:
        filename (str): The full filename, e.g., 'data/optimization_results_0p05_0p05_0p9.csv'.

    Returns:
        list: A list of floats representing the weights.
    """
    # Define a pattern to find the weight part of the filename
    # This looks for any file that starts with "gp_minimize_result_" or "optimization_results_"
    # and ends with a file extension like .pkl or .csv
    pattern = r'(?:gp_minimize_result_|optimization_results_)(.*)\.(?:pkl|csv)'

    match = re.search(pattern, os.path.basename(filename))
    
    if match:
        weights_string = match.group(1)
        # Replace 'p' with '.' and split the string by underscores
        weight_parts = weights_string.replace('p', '.').split('_')
        
        # Convert each string part to a float and return as a list
        try:
            weights = [float(w) for w in weight_parts]
            return weights
        except ValueError:
            print(f"Error: Could not convert weight parts to floats: {weight_parts}")
            return None
    else:
        print(f"Error: Filename format not recognized: {filename}")
        return None

###########################################################################################

from datetime import datetime

def create_run_directory(base_dir="results"):
    """Creates a timestamped results directory structured according to AGENTS.md."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(base_dir, timestamp)
    os.makedirs(os.path.join(run_dir, "gp_checkpoint"), exist_ok=True)
    os.makedirs(os.path.join(run_dir, "figures"), exist_ok=True)
    return run_dir

def save_results(train_X, train_Y, run_dir="mobo_results", hypervolumes=None, constraints_list=None, config=None):
    """Saves the optimization results to JSON and CSV files following AGENTS.md format."""
    os.makedirs(run_dir, exist_ok=True)
    
    if config:
        with open(os.path.join(run_dir, "config.json"), "w") as f:
            json.dump(config, f, indent=2)

    # Save train_X and train_Y
    np.savetxt(os.path.join(run_dir, "train_X.csv"), train_X.numpy(), delimiter=",",
               header=','.join([f"param_{i}" for i in range(train_X.shape[1])]))
    np.savetxt(os.path.join(run_dir, "train_Y.csv"), train_Y.numpy(), delimiter=",",
               header="emit_x_neg,emit_y_neg,sigma_energy_neg")

    # Save Pareto front (un-negated objectives and negated)
    pareto_mask = is_non_dominated(train_Y)
    pareto_Y_neg = train_Y[pareto_mask]
    pareto_Y_orig = -pareto_Y_neg
    pareto_X = train_X[pareto_mask]
    
    pareto_data = np.hstack([pareto_X.numpy(), pareto_Y_orig.numpy()])
    headers_X = [f"param_{i}" for i in range(train_X.shape[1])]
    headers_Y = ["emit_x", "emit_y", "sigma_energy"]
    np.savetxt(os.path.join(run_dir, "pareto.csv"), pareto_data, delimiter=",",
               header=','.join(headers_X + headers_Y))

    # Save hypervolume history if provided
    if hypervolumes is not None:
        np.savetxt(os.path.join(run_dir, "hypervolume.csv"), np.array(hypervolumes), delimiter=",",
                   header="hypervolume")

    # Save constraints diagnostics if provided
    if constraints_list is not None and len(constraints_list) > 0:
        import pandas as pd
        df_c = pd.DataFrame(constraints_list)
        df_c.to_csv(os.path.join(run_dir, "constraints.csv"), index=False)

    print(f"All optimization results saved to {run_dir}/")

###########################################################################################

def save_checkpoint(iteration, train_X, train_Y, train_feas_mask, hypervolumes, 
                    train_constraints_list=None, acquisition_mode='qLogNEHVI', 
                    checkpoint_file="mobo_results/mobo_checkpoint.pt"):
    """Saves the current state of the Bayesian Optimization."""
    # Ensure directory exists for checkpoint_file
    os.makedirs(os.path.dirname(checkpoint_file), exist_ok=True)
    checkpoint_data = {
        'iteration': iteration,
        'train_X': train_X,
        'train_Y': train_Y,
        'train_feas_mask': train_feas_mask,
        'hypervolumes': hypervolumes,
        'train_constraints_list': train_constraints_list,
        'acquisition_mode': acquisition_mode
    }
    torch.save(checkpoint_data, checkpoint_file)
    print(f"Checkpoint saved at iteration {iteration} to {checkpoint_file}")

###########################################################################################

def load_checkpoint(checkpoint_file="mobo_results/mobo_checkpoint.pt"):
    """Loads the state of the Bayesian Optimization from a checkpoint."""
    if os.path.exists(checkpoint_file):
        print(f"Loading checkpoint from {checkpoint_file}...")
        checkpoint_data = torch.load(checkpoint_file, weights_only=False)
        print(f"Checkpoint loaded. Resuming from iteration {checkpoint_data['iteration'] + 1}.")
        return checkpoint_data
    else:
        print("No checkpoint found. Starting new optimization.")
        return None

    