[pytest]
pythonpath = src
testpaths = tests
markers =
    integration: mark test as an integration test running real ASTRA simulations.
filterwarnings =
    ignore::DeprecationWarning:astra.*:
    ignore::DeprecationWarning:pmd_beamphysics.*:
    ignore::PendingDeprecationWarning:beamphysics.*:
    ignore::PendingDeprecationWarning:pmd_beamphysics.*:
    ignore:The set_under function will be deprecated:PendingDeprecationWarning:
    ignore::botorch.exceptions.warnings.NumericsWarning:


