[pytest]
pythonpath = src
testpaths = tests
markers =
    integration: mark test as an integration test running real ASTRA simulations.
filterwarnings =
    ignore::DeprecationWarning:astra.*:
    ignore::DeprecationWarning:pmd_beamphysics.*:
    ignore::botorch.exceptions.warnings.NumericsWarning:

